[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 5173
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"   # Node 패키지 함께 번들링
